import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./_components/contexts/authProvider";
import { ThemeProvider } from "./_components/contexts/themeProvider";
import { Navbar } from "./_components/Navbar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            inter.className
          )}
        >
          <AuthContextProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              // enableSystem
              // disableTransitionOnChange
            >
              <Navbar />

              {children}
            </ThemeProvider>
          </AuthContextProvider>
        </body>
      </html>
    </>
  );
}
